apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: ticket-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: shel404/booking-service:2.0
          ports:
            - containerPort: 3331
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@10.0.2.193:5432/booking"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: ticket-system
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 3331
      targetPort: 3331
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: booking-service
