apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-service
  namespace: ticket-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: train-service
    spec:
      containers:
        - name: train-service
          image: shel404/train-service:2.0
          ports:
            - containerPort: 3333
          env:
            - name: DATABASE_URL
              value: "postgres://live:live@10.0.2.28:5432/train"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: train-service
  namespace: ticket-system
spec:
  selector:
    app: train-service
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: train-service
  namespace: ticket-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: train-service
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
