apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ticket-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: shel404/user-service:2.0
          ports:
            - containerPort: 3330
          env:
            - name: DATABASE_URL
              value: "mongodb+srv://mongo:mongo123@cluster0.1dltw.mongodb.net/userDB"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ticket-system
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3330
      targetPort: 3330
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-service
  namespace: ticket-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
