name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      REPO: shel404

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test user-service
        working-directory: ./services/user-service
        run: |

          npm install
          npm test

      - name: Test booking-service
        working-directory: ./services/booking-service
        run: |

          npm install
          npm test

      - name: Test notification-service
        working-directory: ./services/notification-service
        run: |

          npm install
          npm test

      - name: Test train-service
        working-directory: ./services/train-service
        run: |

          npm install
          npm test

      - name: Test payment-service
        working-directory: ./services/payment-service
        run: |

          npm install
          npm test

      - name: Test frontend
        working-directory: ./frontend
        run: |

          npm install
          npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push user-service image
        run: |
          docker build -t $REGISTRY/$REPO/user-service:2.0 ./services/user-service
          docker push $REGISTRY/$REPO/user-service:2.0

      - name: Build and push booking-service image
        run: |
          docker build -t $REGISTRY/$REPO/booking-service:2.0 ./services/booking-service
          docker push $REGISTRY/$REPO/booking-service:2.0

      - name: Build and push notification-service image
        run: |
          docker build -t $REGISTRY/$REPO/notification-service:2.0 ./services/notification-service
          docker push $REGISTRY/$REPO/notification-service:2.0

      - name: Build and push train-service image
        run: |
          docker build -t $REGISTRY/$REPO/train-service:2.0 ./services/train-service
          docker push $REGISTRY/$REPO/train-service:2.0

      - name: Build and push payment-service image
        run: |
          docker build -t $REGISTRY/$REPO/payment-service:2.0 ./services/payment-service
          docker push $REGISTRY/$REPO/payment-service:2.0

      - name: Build and push frontend image
        run: |
          docker build -t $REGISTRY/$REPO/frontend:2.0 ./frontend
          docker push $REGISTRY/$REPO/frontend:2.0

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME
